version: '3'

services:
  test-111:
    image: local/111-tests:${BUILD_TAG}
    command: ./gradlew -i --build-cache integrationTest
    networks:
      - dbnetwork
    # ports:
    #   - "8080:8080"

  rabbitmq:
    image: 'rabbitmq:3.6-management-alpine'
    networks:
      - dbnetwork
    # ports:
    #   - '5672:5672'
    #   - '15672:15672'

networks:
  dbnetwork:
    name: dbnetwork
