version: '3'

services:
  integration-adaptor-111:
    #image: uk.nhs/integration-adaptor-111:0.0.1-SNAPSHOT
    build:
      context: ./../../
      dockerfile: Dockerfile.111
    ports:
      - "10001:8080"
    environment:
      - PEM111_AMQP_BROKER=amqp://activemq:5672
      - LOG_LEVEL=DEBUG
    depends_on: 
      - activemq

  nginx:
    build:
      context: ./../../
      dockerfile: Dockerfile.nginx
    ports:
      - 8080:80
      - 8083:443
    depends_on:
      - integration-adaptor-111

  activemq:
    image: rmohr/activemq:5.15.9
    ports:
      - "8161:8161"
      - "5672:5672"
  