amqp:
  broker: ${PEM111_AMQP_BROKER:amqp://localhost:5672}
  queueName: ${PEM111_AMQP_QUEUE_NAME:encounter-report-test}
  exchange: amq.direct
  username: ${PEM111_AMQP_USERNAME:}
  password: ${PEM111_AMQP_PASSWORD:}

soap:
  sendTo: ${PEM111_SOAP_SEND_TO:http://localhost:8080/report}